package br.com.cis;

/**
 * @author LuisBogea
 *
 */
public enum LsReply {
	
    LS_OKAY(0, "Success"),
    LS_SYSTEM_ERROR(-1, "The service was unable to execute command due to a system error."),
    LS_USB_ERROR(-2, "The service was unable to execute a command due to a USB error"),
    LS_PERIPHERAL_NOT_FOUND(-3, "Peripheral not found"),
    LS_HARDWARE_ERROR(-4, "Hardware error"),
    LS_PERIPHERAL_OFF_ON(-5, "Peripheral OFF and ON again"),
    LS_RESERVED_ERROR(-6, "Reserved error"),
    LS_PAPER_JAM(-7, "Paper jam"),
    LS_TARGET_BUSY(-8, "Target busy"),
    LS_INVALID_COMMAND(-9, "Invalid command"),
    LS_DATA_LOST(-10, "Data lost"),
    LS_COMMAND_IN_EXECUTION_YET(-11, "Command in execution yet"),
    LS_JPEG_ERROR(-12, "JPEG error"),
    LS_COMMAND_SEQUENCE_ERROR(-13, "Command sequence error"),
    LS_PC_HW_ERROR(-14, "Hardware error"),
    LS_IMAGE_OVERWRITE(-15, "Image overwrite"),
    LS_INVALID_HANDLE(-16, "Invalid handle"),
    LS_NO_LIBRARY_LOAD(-17, "No library loaded."),
    LS_BMP_ERROR(-18, "BMP error"),
    LS_TIFF_ERROR(-19, "TIFF error"),
    LS_IMAGE_NO_MORE_AVAILABLE(-20, "Image no more available"),
    LS_IMAGE_NO_FILMED(-21, "Image no filmed"),
    LS_IMAGE_NOT_PRESENT(-22, "Image no present"),
    LS_FUNCTION_NOT_AVAILABLE(-23, "Function not available"),
    LS_DOCUMENT_NOT_SUPPORTED(-24, "Document not supported"),
    LS_BARCODE_ERROR(-25, "Barcode error"),
    LS_INVALID_LIBRARY(-26, "Invalid library"),
    LS_INVALID_IMAGE(-27, "Invalid image"),
    LS_INVALID_IMAGE_FORMAT(-28, "Invalid image format"),
    LS_INVALID_BARCODE_TYPE(-29, "Invalid barcode type"),
    LS_OPEN_NOT_DONE(-30, "Open not done"),
    LS_INVALID_TYPE_COMMAND(-31, "Invalid type command"),
    LS_INVALID_CLEARBLACK(-32, "Invalid clear black"),
    LS_INVALID_SIDE(-33, "Invalid side"),
    LS_MISSING_IMAGE(-34, "Missing image"),
    LS_INVALID_TYPE(-35, "Invalid type"),
    LS_INVALID_SAVEMODE(-36, "Invalid save mode"),
    LS_INVALID_PAGE_NUMBER(-37, "Invalid page number"),
    LS_INVALID_NRIMAGE(-38, "Invalid NR image"),
    LS_INVALID_STAMP(-39, "Invalid stamp"),
    LS_INVALID_WAITTIMEOUT(-40, "Invalid wait timeout"),
    LS_INVALID_VALIDATE(-41, "Invalid validate"),
    LS_INVALID_CODELINE_TYPE(-42, "Invalid codeline type"),
    LS_MISSING_NRIMAGE(-43, "Missing NR image"),
    LS_INVALID_SCANMODE(-44, "Invalid scan mode"),
    LS_INVALID_BEEP(-45, "Invalid beep"),
    LS_INVALID_FEEDER(-46, "Invalid feeder"),
    LS_INVALID_SORTER(-47, "Invalid sorter"),
    LS_INVALID_BADGE_TRACK(-48, "Invalid badge track"),
    LS_MISSING_FILENAME(-49, "Missing file name"),
    LS_INVALID_QUALITY(-50, "Invalid quality"),
    LS_INVALID_FILEFORMAT(-51, "Invalid file format"),
    LS_INVALID_COORDINATE(-52, "Invalid coordinate"),
    LS_MISSING_HANDLE_VARIABLE(-53, "Missing handle variable"),
    LS_INVALID_POLO_FILTER(-54, "Invalid polo filter"),
    LS_INVALID_ORIGIN_MEASURES(-55, "Invalid origin measures"),
    LS_INVALID_SIZEH_VALUE(-56, "Invalid sizeH value"),
    LS_INVALID_FORMAT(-57, "Invalid format"),
    LS_STRINGS_TOO_LONGS(-58, "String too long"),
    LS_READ_IMAGE_FAILED(-59, "Read image failed"),
    LS_INVALID_CMD_HISTORY(-60, "Invalid command history"),
    LS_MISSING_BUFFER_HISTORY(-61, "Missing buffer history"),
    LS_INVALID_ANSWER(-62, "Invalid answer"),
    LS_OPEN_FILE_ERROR_OR_NOT_FOUND(-63, "Open file error or not found"),
    LS_READ_TIMEOUT_EXPIRED(-64, "Read timeout expired"),
    LS_INVALID_METHOD(-65, "Invalid method"),
    LS_CALIBRATION_FAILED(-66, "Callibration failed"),
    LS_INVALID_SAVEIMAGE(-67, "Invalid save image"),
    LS_INVALID_UNIT(-68, "Invalid unit"),
    LS_INVALID_NRWINDOWS(-71, "Invalid NR Windows"),
    LS_INVALID_VALUE(-72, "Invalid value"),
    LS_ILLEGAL_REQUEST(-73, "Illegal request"),
    LS_INVALID_NR_CRITERIA(-74, "Invalid NR criteria"),
    LS_MISSING_CRITERIA_STRUCTURE(-75, "Missing criteria structure"),
    LS_INVALID_MOVEMENT(-76, "Invalid moviment"),
    LS_INVALID_DEGREE(-77, "Invalid degree"),
    LS_R0TATE_ERROR(-78, "Rotate error"),
    LS_MICR_VALUE_OUT_OF_RANGE(-79, "MICR value out of range"),
    LS_PERIPHERAL_RESERVED(-80, "Peripheral reserved"),
    LS_INVALID_NCHANGE(-81, "Invalid N change"),
    LS_BRIGHTNESS_ERROR(-82, "Brightness error"),
    LS_CONTRAST_ERROR(-83, "Contrast error"),
    LS_INVALID_SIDETOPRINT(-84, "Invalid side to print"),
    LS_DOUBLE_LEAFING_ERROR(-85, "Double leaf error"),
    LS_INVALID_BADGE_TIMEOUT(-86, "Invalid badge timeout"),
    LS_INVALID_RESET_TYPE(-87, "Invalid reset timeout"),
    LS_MISSING_SET_CALLBACK(-88, "Missing set callback"),
    LS_IMAGE_NOT_200_DPI(-89, "Image not 200 DPI"),
    LS_DOWNLOAD_ERROR(-90, "Download error"),
    LS_INVALID_SORT_ON_CHOICE(-91, "Invalid sort on choice"),
    LS_INVALID_FONT(-92, "Invalid font"),
    LS_INVALID_UNIT_SPEED(-93, "Invalid unit speed"),
    LS_INVALID_LENGTH(-94, "Invalid length"),
    LS_SHORT_PAPER(-95, "Short paper"),
    LS_INVALID_DOC_LENGTH(-96, "Invalid document length"),
    LS_INVALID_DOCSLONG(-97, "Invalid document long"),
    LS_IMAGE_NOT_256_COLOR(-98, "Image not 256 color"),
    LS_BATTERY_NOT_CHARGED(-99, "Battery not charged"),
    LS_INVALID_SCAN_DOC_TYPE(-100, "Invalid scan doc type"),
    LS_ILLEGAL_SCAN_CARD_SPEED(-101, "Illegal sscan card speed"),
    LS_INVALID_PWM_VALUE(-102, "Invalid PWM value"),
    LS_INVALID_KEY_LENGTH(-103, "Invalid key length"),
    LS_INVALID_PASSWORD(-104, "Invalid password"),
    LS_UNIT_LOCKED(-105, "Unit locked"),
    LS_INVALID_IMAGEFORMAT(-106, "Invalid image format"),
    LS_INVALID_THRESHOLD(-107, "Invalid threshold"),
    LS_NO_START_FOR_SORTER_FULL(-108, "No start for sorter full"),
    LS_IPBOX_ADDRESS_NOT_FOUNDED(-109, "IPBOX address not found"),
    LS_INVALID_LED_COMMAND(-110, "Invalid LED command"),
    LS_INVALID_COLOR_PARAMETER(-111, "Invalid color parameter"),
    LS_JAM_AT_MICR_PHOTO(-201, "Jam at MICR photo"),
    LS_JAM_DOC_TOO_LONG(-202, "Jam, document too long"),
    LS_JAM_AT_SCANNER_PHOTO(-203, "Jam at scanner photo"),
    LS_SCAN_NETTO_IMAGE_NOT_SUPPORTED(-521, "Scan netto image not supported"),
    LS_256_GRAY_NOT_SUPPORTED(-522, "256 gray not supported"),
    LS_INVALID_PATH(-523, "Invalid path"),
    LS_MISSING_CALLBACK_FUNCTION(-526, "Missing calback function"),
    LS_INVALID_OCR_IMAGE_SIDE(-558, "Invalid OCR image side"),
    LS_PERIPHERAL_NOT_ANSWER(-599, "Peripheral not answer"),
    LS_INVALID_CONNECTION_HANDLE(-1000, "Invalid connection handle"),
    LS_INVALID_CONNECT_PERIPHERAL(-1001, "Invalid connection peripheral"),
    LS_PERIPHERAL_NOT_YET_INTEGRATE(-1002, "Peripheral not yet integrate"),
    LS_UNKNOW_PERIPHERAL_REPLY(-1003, "Unknow peripheral reply"),
    LS_CODELINE_ALREADY_DEFINED(-1004, "Codeline already defined"),
    LS_INVALID_NUMBER_OF_DOC(-1005, "Invalid number of document"),
    LS_DECODE_FONT_NOT_PRESENT(-1101, "Decode font not present"),
    LS_DECODE_INVALID_COORDINATE(-1102, "Decode invalid coordinate"),
    LS_DECODE_INVALID_OPTION(-1103, "Decode invalid option"),
    LS_DECODE_INVALID_CODELINE_TYPE(-1104, "Decode invalid codeline type"),
    LS_DECODE_SYSTEM_ERROR(-1105, "Decode system error"),
    LS_DECODE_DATA_TRUNC(-1106, "Decode data trunc"),
    LS_DECODE_INVALID_BITMAP(-1107, "Decode invalid bitmap"),
    LS_DECODE_ILLEGAL_USE(-1108, "Decode illegal use"),
    LS_BARCODE_GENERIC_ERROR(-1201, "Barcode generic error"),
    LS_BARCODE_NOT_DECODABLE(-1202, "Barcode not decodable"),
    LS_BARCODE_OPENFILE_ERROR(-1203, "Barcode open file error"),
    LS_BARCODE_READBMP_ERROR(-1204, "Barcode read BMP error"),
    LS_BARCODE_MEMORY_ERROR(-1205, "Barcode memory error"),
    LS_BARCODE_START_NOTFOUND(-1206, "Barcode start not found"),
    LS_BARCODE_STOP_NOTFOUND(-1207, "Barcode stop not found"),
    LS_PDF_NOT_DECODABLE(-1301, "PDF not decodable"),
    LS_PDF_READBMP_ERROR(-1302, "PDF read BMP error"),
    LS_PDF_BITMAP_FORMAT_ERROR(-1303, "PDF bitmap fomat error"),
    LS_PDF_MEMORY_ERROR(-1304, "PDF memory error"),
    LS_PDF_START_NOTFOUND(-1305, "PDF start not found"),
    LS_PDF_STOP_NOTFOUND(-1306, "PDF stop not found"),
    LS_PDF_LEFTIND_ERROR(-1307, "PDF left ind error"),
    LS_PDF_RIGHTIND_ERROR(-1308, "PDF right ind error"),
    LS_PDF_OPENFILE_ERROR(-1309, "PDF open file error"),
    /*
     * WARNINGS
     */    
    LS_FEEDER_EMPTY(1, "Feeder empty"),
    LS_DATA_TRUNCATED(2, "Data truncated"),
    LS_DOC_PRESENT(3, "Documet present"),
    LS_BADGE_TIMEOUT(4, "Badge timeout"),
    LS_ALREADY_OPEN(5, "Already open"),
    LS_PERIPHERAL_BUSY(6, "Peripheral busy"),
    LS_DOUBLE_LEAFING_WARNING(7, "Double leafing warning"),
    LS_COMMAND_NOT_ENDED(8, "Command not ended"),
    LS_RETRY(9, "Retry"),
    LS_NO_OTHER_DOCUMENT(10, "No other document"),
    LS_QUEUE_FULL(11, "Queue full"),
    LS_NO_SENSE(12, "No sense"),
    LS_TRY_TO_RESET(14, "Try to reset"),
    LS_STRING_TRUNCATED(15, "String truncated"),
    LS_COMMAND_NOT_SUPPORTED(19, "Command not supported"),
    LS_SORTER1_FULL(35, "Sorter 1 full"),
    LS_SORTER2_FULL(36, "Sorter 2 full"),
    LS_SORTERS_BOTH_FULL(37, "Sorters both full"),
    LS_KEEP_DOC_ON_CODELINE_ERROR(39, "Keep doc on codeline error"),
    LS_LOOP_INTERRUPTED(40, "Loop interrupted"),
    LS_SORTER_1_POCKET_1_FULL(51, "Sorter 1 pocket 1 full"),
    LS_SORTER_1_POCKET_2_FULL(52, "Sorter 1 pocket 2 full"),
    LS_SORTER_1_POCKET_3_FULL(53, "Sorter 1 pocket 3 full"),
    LS_SORTER_2_POCKET_1_FULL(54, "Sorter 2 pocket 1 full"),
    LS_SORTER_2_POCKET_2_FULL(55, "Sorter 2 pocket 2 full"),
    LS_SORTER_2_POCKET_3_FULL(56, "Sorter 2 pocket 3 full"),
    LS_SORTER_3_POCKET_1_FULL(57, "Sorter 3 pocket 1 full"),
    LS_SORTER_3_POCKET_2_FULL(58, "Sorter 3 pocket 2 full"),
    LS_SORTER_3_POCKET_3_FULL(59, "Sorter 3 pocket 3 full"),
    LS_SORTER_4_POCKET_1_FULL(60, "Sorter 4 pocket 1 full"),
    LS_SORTER_4_POCKET_2_FULL(61, "Sorter 4 pocket 2 full"),
    LS_SORTER_4_POCKET_3_FULL(62, "Sorter 4 pocket 3 full"),
    LS_SORTER_5_POCKET_1_FULL(63, "Sorter 5 pocket 1 full"),
    LS_SORTER_5_POCKET_2_FULL(64, "Sorter 5 pocket 2 full"),
    LS_SORTER_5_POCKET_3_FULL(65, "Sorter 5 pocket 3 full"),
    LS_SORTER_6_POCKET_1_FULL(66, "Sorter 6 pocket 1 full"),
    LS_SORTER_6_POCKET_2_FULL(67, "Sorter 6 pocket 2 full"),
    LS_SORTER_6_POCKET_3_FULL(68, "Sorter 6 pocket 3 full"),
    LS_SORTER_7_POCKET_1_FULL(69, "Sorter 7 pocket 1 full"),
    LS_SORTER_7_POCKET_2_FULL(70, "Sorter 7 pocket 2 full"),
    LS_SORTER_7_POCKET_3_FULL(71, "Sorter 7 pocket 3 full");
    
	private final int value;
	private final String errorMessage;

	/**
	 * @param value
	 * @param errorMessage
	 */
	LsReply( int value, String errorMessage) {
		this.value = value;
		this.errorMessage = errorMessage;
	}

	/**
	 * @return int error value
	 */
	public int getValue() {
		return this.value;
	}
	
	/**
	 * @return String error message
	 */
	public String getErrorMessage() {
		return errorMessage;
	}
        
}

